fix: resume the pre merge steps

diff --git a/.github/workflows/build-release.yaml b/.github/workflows/build-release.yaml
--- a/.github/workflows/build-release.yaml
+++ b/.github/workflows/build-release.yaml
@@ -50,28 +50,18 @@ jobs:
             RESPONSE=$(curl -s "https://api.github.com/repos/bcgov/java-maven-pipeline-example/pulls?head=bcgov:${{ github.head_ref || github.ref_name }}&state=open&base=main" \
               -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github+json")
-            echo "PR Response 1: $RESPONSE"
-            if [[ -z "$RESPONSE" || "$RESPONSE" == "null" || $(echo "$RESPONSE" | jq -e '. | length' 2>/dev/null) -eq 0 ]]; then
-              echo "checkout_ref=${{ github.ref_name }}" >> $GITHUB_OUTPUT
-
-              REF_NAME="${{ github.ref_name }}"
-              SAFE_REF_NAME=$(echo "$REF_NAME" | tr '/' '-')
-              echo "version_modifier=${SAFE_REF}" >> $GITHUB_OUTPUT
-            else
-              PULL_REQUEST_NUMBER=$(echo "${RESPONSE}" | jq -r .[0].number)
-              RESPONSE=$(curl -s "https://api.github.com/repos/bcgov/java-maven-pipeline-example/pulls/$PULL_REQUEST_NUMBER" \
-                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-                -H "Accept: application/vnd.github+json")
-
-              MERGEABLE=$(echo "${RESPONSE}" | jq -r .mergeable)
-              if [[ "$MERGEABLE" != "true" ]]; then
-                echo "::error ::Pull request #$PULL_REQUEST_NUMBER is not mergeable… aborted."
-                echo "This can be resolved by resolving the merge conflict with the main branch."
-                exit 1
-              fi
-              echo "checkout_ref=refs/pull/$PULL_REQUEST_NUMBER/merge" >> $GITHUB_OUTPUT
-              echo "version_modifier=$PULL_REQUEST_NUMBER" >> $GITHUB_OUTPUT
+            PULL_REQUEST_NUMBER=$(echo "${RESPONSE}" | jq -r .[0].number)
+            RESPONSE=$(curl -s "https://api.github.com/repos/bcgov/java-maven-pipeline-example/pulls/$PULL_REQUEST_NUMBER" \
+              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+              -H "Accept: application/vnd.github+json")
+            MERGEABLE=$(echo "${RESPONSE}" | jq -r .mergeable)
+            if [[ "$MERGEABLE" != "true" ]]; then
+              echo "::error ::Pull request #$PULL_REQUEST_NUMBER is not mergeable… aborted."
+              echo "This can be resolved by resolving the merge conflict with the main branch."
+              exit 1
             fi
+            echo "checkout_ref=refs/pull/$PULL_REQUEST_NUMBER/merge" >> $GITHUB_OUTPUT
+            echo "version_modifier=$PULL_REQUEST_NUMBER" >> $GITHUB_OUTPUT
           else
             echo "checkout_ref=${{ github.ref_name }}" >> $GITHUB_OUTPUT
             echo "version_modifier=${{ github.ref_name }}" >> $GITHUB_OUTPUT
