feat: add indents

diff --git a/.github/workflows/check-token.yaml b/.github/workflows/check-token.yaml
--- a/.github/workflows/check-token.yaml
+++ b/.github/workflows/check-token.yaml
@@ -22,17 +22,17 @@ jobs:
         shell: bash
         run: |
           RESPONSE_CODE=$(curl -o /dev/null -s -w "%{http_code}" -X 'GET' \
-          ${{ inputs.url }}/v1/health/token-check \
-          -H 'accept: */*' \
-          -H 'Authorization: Bearer '"${{ secrets.token }}"'' \
+            ${{ inputs.url }}/v1/health/token-check \
+            -H 'accept: */*' \
+            -H 'Authorization: Bearer '"${{ secrets.token }}"'' \
           )
 
           if [ "$RESPONSE_CODE" -eq 401 ]; then
-          echo "Unauthorized (401)"
-          exit 1
+            echo "Unauthorized (401)"
+            exit 1
           elif [ "$RESPONSE_CODE" -eq 403 ]; then
-          echo "Invalid JWT: Block list has match"
-          exit 1
+            echo "Invalid JWT: Block list has match"
+            exit 1
           else
-          echo "Response code: $RESPONSE_CODE"
+            echo "Response code: $RESPONSE_CODE"
           fi
